import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import ToggleProvider from "@/context/ToggleProvider/ToggleProvider";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Toaster } from "sonner";
import PanelNavbar from "@/component/PanelNavbar/PanelNavbar";
import MainHeader from "@/component/MainHeader/MainHeader";
import QueryProvider from "@/context/QueryProvider/QueryProvider";
import { PreferenceProvider } from "@/context/PreferenceProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { DropdownMenu } from "@/component/DropdownMenu/DropdownMenu";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BareStore RMS ",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable} ${OutfitFont.variable}`}>
        <QueryProvider>
          <PreferenceProvider>
            <DropdownMenu>
              <Toaster position="top-center" duration={5000} />
              <NextTopLoader showSpinner={false} color="var(--color-primary)" />
              <ToggleProvider>
                <div
                  style={{
                    display: "flex",
                    flexDirection: "row",
                    height: "100vh",
                  }}
                >
                  <PanelNavbar />
                  <div
                    style={{
                      flex: 1,
                      display: "flex",
                      flexDirection: "column",
                      overflow: "hidden",
                      minWidth: 0,
                    }}
                  >
                    <MainHeader />
                    {children}
                  </div>
                </div>
              </ToggleProvider>
            </DropdownMenu>
          </PreferenceProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryProvider>
      </body>
    </html>
  );
}
