import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import ToggleProvider from "@/context/ToggleProvider/ToggleProvider";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable} ${OutfitFont.variable}`}>
        <NextTopLoader showSpinner={false} color="var(--blue-500)" />
        <ToggleProvider>{children}</ToggleProvider>
      </body>
    </html>
  );
}
